### ISSUE TITLE
Zeit does not allow new users to deploy Now V1 apps

### ISSUE THREAD

**Issue by JonathanJonathanJonathan** [ropnop/serverless_toolkit#1]
Thanks for sharing this toolkit! However I've some trouble using it; see https://github.com/zeit/now/issues/1805

**Comment by jthack** [comment]
I am having this issue as well

**Comment by ropnop** [comment]
I was afraid that was gonna happen eventually. Can you test out the branch in #2 and verify the functions deploy correctly for you on Zeit with Version 2?

**Comment by jthack** [comment]
git pull -> everything is fine now. thanks @ropnop

**Comment by ropnop** [comment]
Awesome! Glad to hear
